### PR TITLE
Added args and file reading

### PR DESCRIPTION
**Pull request by dmadisetti**

### CODE REVIEW

**Comment by kevinlmadison** [comment]
So is the master.rs file something that will be generated by protobuf?

**Comment by dmadisetti** [comment]
Yes. Try running it yourself. You'll need to install protoc and "cargo install protobuf", but then the script build should do it for you

**Comment by pbateman828** [comment]
Yo, I'm getting an error.  
-------------------------------------------------------------------------------
 --> src/protos/mod.rs:2:9
  |
2 | pub mod master;
  |         ^^^^^^
  |
  = help: name the file either master.rs or master/mod.rs inside the directory "src/protos"
------------------------------------------------------------------------------------------------------------- 
I tried renaming the file but no luck

**Comment by kevinlmadison** [comment]
@pbateman828 do the following:
> cargo install protobuf
> sudo apt-get install protobuf-compiler
> ./build.sh
> cargo build

**Comment by pbateman828** [comment]
nevermind, i was trying to run it without protoc and running build.sh

**Review by kevinlmadison — APPROVED** [review]
looks good to me

**Pull request merged**
