### PR TITLE
Added readline feature.

### PR DESCRIPTION
**Pull request by dmadisetti**

### CODE REVIEW

**Comment by dmadisetti** [comment]
https://github.com/AnotherGroupChat/maeve/issues/4

**Review by pbateman828 — APPROVED** [review]
Nice

**Comment by kevinlmadison** [comment]
How do I run it with the pretty prompt?

**Comment by kevinlmadison** [comment]
ah I got it, 
cargo run --features pretty
nice!

**Review by kevinlmadison — APPROVED** [review]
noice

**Pull request merged**
